name: Build Setup
description: Setup for standard Java builds

runs:
  using: "composite"

  steps:

  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: zulu
      java-version: 17

  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      generate-job-summary: false
