# Runs tests and formatting requirements
name: Java Checks

on:
  push:
    branches:
      - master
    paths: ['src/main/java', 'src/test', 'gradle/**', '**.gradle', 'gradle.properties', 'gradlew**']
  pull_request:
    paths: ['src/main/java', 'src/test', 'gradle/**', '**.gradle', 'gradle.properties', 'gradlew**']

concurrency:
  group: checks-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java Environment
        uses: TechLord22/ci-experiments/.github/workflows/setup_java_environment.yml

      - name: Run Tests with Gradle
        run: ./gradlew test --warning-mode all --build-cache

  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Run Spotless Formatting with Gradle
        run: ./gradlew spotlessCheck --warning-mode all --build-cache
