name: Java Build Environment Setup

on:
  workflow_call:
    inputs:
      description: If cache should be updated
      required: false
      default: false
      type: boolean

jobs:
  setup:
    name: Setup Java Build Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-write-only: ${{ inputs.update-cache }}
        generate-job-summary: false
        gradle-home-cache-includes: |
          caches
          caches/retro_futura_gradle
          notifications
          jdks
          wrapper
