# Updates the Gradle Cache when necessary
name: Update Gradle Cache

on:
  push:
    branches:
      - master
    paths: ['gradle/**', '**.gradle', 'gradle.properties', 'gradlew**']
  workflow_dispatch:

concurrency:
  group: gradle-cache-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-cache:
    name: Update Grade Cache
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java Environment
        uses: TechLord22/ci-experiments/.github/workflows/setup_java_environment.yml
        with:
          update-cache: true

      - name: Build Project with Gradle
        run: ./gradlew assemble --warning-mode all --build-cache
