# Updates the Gradle Cache when necessary
name: Update Gradle Cache

on:
  push:
    branches:
      - master
    paths: ['gradle/**', '**.gradle', 'gradle.properties', 'gradlew**']
  workflow_dispatch:

concurrency:
  group: gradle-cache-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-cache:
    name: Update Grade Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup
        with:
          update-cache: true

      - name: Run Tests with Gradle
        run: ./gradlew test --warning-mode all --build-cache
